spring:
  config:
    import: "optional:zookeeper:"
  application:
    name: HelloWorld
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
